# Generated by Django 2.2.8 on 2020-05-29 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='when',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
