# Generated by Django 2.2.8 on 2020-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('cup_vol', models.IntegerField(default=200)),
            ],
        ),
    ]
