# Generated by Django 2.2.8 on 2020-05-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferences',
            options={'verbose_name_plural': 'Preferences'},
        ),
    ]
