# Generated by Django 2.2.8 on 2020-05-29 12:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_auto_20200529_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0.01, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
