# Generated by Django 2.2.8 on 2020-07-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0006_auto_20200601_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
