# Generated by Django 2.2.8 on 2020-07-21 18:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0007_preferences_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='is_male',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.01, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
