# Generated by Django 2.2.8 on 2020-07-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0008_auto_20200721_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='cup_vol',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
