# Generated by Django 2.2.8 on 2020-08-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0009_auto_20200722_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='is_male',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
